import PDFDocument from "pdfkit";
import { generateQrPngBuffer } from "./qr.service";
import { config } from "../config/env";

export interface ReceiptData {
  institutionName: string;
  institutionLogoUrl?: string | null;
  collectionName: string;
  studentName: string;
  studentPin: string;
  studentClass: string;
  utr: string;
  amount: number;
  paymentDate: Date;
  status: "APPROVED" | "PENDING" | "REJECTED";
  receiptNumber: string;
}

const GREEN = "#15803d";
const SLATE = "#334155";
const LIGHT_SLATE = "#64748b";
const BORDER = "#e2e8f0";

export async function generateReceiptPdf(data: ReceiptData): Promise<Buffer> {
  const verifyUrl = `${config.publicAppUrl}/verify/${data.receiptNumber}`;
  const qrBuffer = await generateQrPngBuffer(verifyUrl);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc
      .fillColor(SLATE)
      .fontSize(20)
      .font("Helvetica-Bold")
      .text(data.institutionName, 50, 50);

    doc
      .fillColor(LIGHT_SLATE)
      .fontSize(11)
      .font("Helvetica")
      .text("Official Payment Receipt", 50, 76);

    doc
      .moveTo(50, 105)
      .lineTo(545, 105)
      .strokeColor(BORDER)
      .lineWidth(1)
      .stroke();

    // Status badge
    const statusColor =
      data.status === "APPROVED" ? GREEN : data.status === "REJECTED" ? "#dc2626" : "#d97706";
    doc
      .fillColor(statusColor)
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(data.status, 450, 50, { width: 95, align: "right" });

    // Receipt number
    doc
      .fillColor(SLATE)
      .fontSize(14)
      .font("Helvetica-Bold")
      .text(data.receiptNumber, 50, 125);

    doc
      .fillColor(LIGHT_SLATE)
      .fontSize(9)
      .font("Helvetica")
      .text(`Issued ${new Date().toLocaleString("en-IN")}`, 50, 145);

    // Details table
    const rows: [string, string][] = [
      ["Collection", data.collectionName],
      ["Student Name", data.studentName],
      ["PIN", data.studentPin],
      ["Class", data.studentClass],
      ["UTR / Transaction Ref", data.utr],
      ["Amount", `Rs. ${data.amount.toFixed(2)}`],
      ["Payment Date", data.paymentDate.toLocaleString("en-IN")],
    ];

    let y = 185;
    for (const [label, value] of rows) {
      doc.fillColor(LIGHT_SLATE).fontSize(10).font("Helvetica").text(label, 50, y, { width: 180 });
      doc.fillColor(SLATE).fontSize(11).font("Helvetica-Bold").text(value, 240, y, { width: 255 });
      y += 28;
    }

    doc.moveTo(50, y + 10).lineTo(545, y + 10).strokeColor(BORDER).stroke();

    // QR code + verification note
    doc.image(qrBuffer, 50, y + 30, { width: 110, height: 110 });
    doc
      .fillColor(SLATE)
      .fontSize(10)
      .font("Helvetica-Bold")
      .text("Scan to verify this receipt", 175, y + 35, { width: 320 });
    doc
      .fillColor(LIGHT_SLATE)
      .fontSize(9)
      .font("Helvetica")
      .text(
        `Or visit: ${verifyUrl}`,
        175,
        y + 55,
        { width: 320 }
      );
    doc
      .fillColor(LIGHT_SLATE)
      .fontSize(8)
      .font("Helvetica")
      .text(
        "This receipt is system-generated and can be independently verified using the QR code or link above. It does not require a physical signature.",
        175,
        y + 80,
        { width: 320 }
      );

    doc
      .fillColor(LIGHT_SLATE)
      .fontSize(8)
      .text(
        `Generated by Class Payment Tracker Pro on behalf of ${data.institutionName}`,
        50,
        770,
        { align: "center", width: 495 }
      );

    doc.end();
  });
}
